#!/bin/bash

timestamp=$(date '+%Y-%m-%d-%H-%M-%S')
file="ss_$timestamp.png"

shotgun "$file"

mv $file "$(xdg-user-dir PICTURES)/screenshots"

noswallow_open "sxiv '$(xdg-user-dir PICTURES)'/screenshots/'$file'"
