#!/bin/bash

style=$(cat $HOME/.config/dunst/sid)

pulsemixer --change-volume -5 && pulsemixer --unmute && dunstify -u low --replace=69 -i /usr/share/icons/Hybrid/status/24/audio-volume-medium.svg "Volume Down : $(volume)%"
#old
#amixer -Mq set Master,0 5%+ unmute
